### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by ghost** [ruanpienaar/nimby#1]
Interesting library, could have potential, needs license file. My vote is Apache 2.

**Comment by ruanpienaar** [comment]
Done https://github.com/ruanpienaar/nimby/commit/de397f20df7656ca1dd4b9e1708d142ef63f6a22

**Comment by ghost** [comment]
GPL is not much use for something most likely embedded in an Apache 2
project

**Comment by ruanpienaar** [comment]
OOPS! don't know how that happened...
