### ISSUE TITLE
Riak mapreduce job encoding

### ISSUE THREAD

**Issue by ghost** [ruanpienaar/nimby#2]
Would be interesting to see if it could be embedded into Riak, receive mapreduce requests, decode them and execute them successfully. Perhaps we could work on this together.

**Comment by ruanpienaar** [comment]
the one bit of work i needed some futher studying on was apply.
When something remotely has to be done, i currently use erlang:apply(M, F, A).
Which may/may-not be test best idea.
I've tried digging through rex and rpc, to see how they prepare the MFA's.
